import 'constants.dart';

/// Affirmationsvorschläge organisiert nach Kategorie und Level
/// Insgesamt 240 Sätze: 4 Kategorien × 3 Levels × 20 Sätze
/// Level 1 → levelBeginner (Anfänger) - 20 Sätze
/// Level 2 → levelAdvanced (Fortgeschritten) - 20 Sätze
/// Level 3 → levelOpen (Offen) - 20 Sätze
class AffirmationSuggestions {
  static final Map<String, Map<String, List<String>>> suggestions = {
    // Kategorie: Selbstbewusstsein
    AppConstants.categorySelbstbewusstsein: {
      AppConstants.levelBeginner: [
        'Ich darf klein anfangen.',
        'Ich übe, mich zu zeigen – Schritt für Schritt.',
        'Es ist okay, nervös zu sein.',
        'Meine Stimme verdient Raum.',
        'Ich bin heute mutiger als gestern.',
        'Ich kann Neues lernen.',
        'Fehler sind erlaubt und hilfreich.',
        'Ich darf langsam gehen.',
        'Ich darf Grenzen setzen.',
        'Ich nehme mich freundlich wahr.',
        'Ich darf Pausen machen.',
        'Ich kann um Hilfe bitten.',
        'Ich übe, Blickkontakt zu halten.',
        'Ich darf „Nein" sagen.',
        'Ich bin hier willkommen.',
        'Ich muss nicht perfekt sein.',
        'Ich darf meinen Platz einnehmen.',
        'Ich darf meine Meinung sagen.',
        'Ich traue mir den nächsten kleinen Schritt zu.',
        'Ich gehe freundlich mit mir um.',
      ],
      AppConstants.levelAdvanced: [
        'Ich trete klar und ruhig auf.',
        'Ich vertraue meinem Gefühl und prüfe nach.',
        'Ich spreche deutlich und mit Ruhe.',
        'Meine Meinung hat Gewicht.',
        'Ich setze klare Grenzen und bleibe respektvoll.',
        'Ich vertraue meiner Vorbereitung.',
        'Ich handle, auch wenn ich Unsicherheit spüre.',
        'Ich lerne aus Rückmeldungen.',
        'Ich halte Blickkontakt und atme ruhig.',
        'Ich entscheide und stehe dazu.',
        'Ich erkenne meine Fortschritte an.',
        'Ich darf sichtbar sein.',
        'Ich kann mit Fehlern souverän umgehen.',
        'Ich formuliere Wünsche klar.',
        'Ich achte meine Zeit und Energie.',
        'Ich bleibe bei mir – auch in Gruppen.',
        'Ich kann Nein sagen, ohne mich zu rechtfertigen.',
        'Ich nehme Lob an.',
        'Ich traue mir größere Schritte zu.',
        'Ich bin verlässlich – mir selbst und anderen gegenüber.',
      ],
      AppConstants.levelOpen: [
        'Ich betrete Räume mit Präsenz.',
        'Meine innere Ruhe strahlt nach außen.',
        'Ich beeinflusse Situationen konstruktiv.',
        'Ich wähle mutig, was mir entspricht.',
        'Ich formuliere klar und wirke.',
        'Ich bin Quelle von Orientierung.',
        'Ich verkörpere meine Werte sichtbar.',
        'Ich führe Gespräche bewusst und lenkend.',
        'Ich vertraue meiner Intuition und setze um.',
        'Ich bin standhaft und flexibel zugleich.',
        'Ich inspiriere durch mein Beispiel.',
        'Ich erhebe meine Stimme für Wichtiges.',
        'Ich nehme Raum ein – respektvoll und bestimmt.',
        'Ich verhandle auf Augenhöhe.',
        'Ich treffe Entscheidungen mit Gelassenheit.',
        'Ich bleibe präsent – auch unter Druck.',
        'Ich stehe für mich ein ohne Kampf.',
        'Ich bin wirksam in meinem Handeln.',
        'Ich erweitere bewusst meine Komfortzone.',
        'Ich strahle Selbstsicherheit aus.',
      ],
    },

    // Kategorie: Selbstwert
    AppConstants.categorySelbstwert: {
      AppConstants.levelBeginner: [
        'Ich behandle mich freundlich.',
        'Ich verdiene Ruhe und Nahrung.',
        'Ich darf Bedürfnisse haben.',
        'Ich darf Fehler machen und lernen.',
        'Ich bin genug für den nächsten Schritt.',
        'Ich spreche innerlich respektvoll mit mir.',
        'Ich bin wichtig in meinem Leben.',
        'Ich darf Hilfe annehmen.',
        'Ich achte meine Grenzen.',
        'Ich würdige kleine Fortschritte.',
        'Ich bin mehr als meine Leistung.',
        'Ich darf Neues ausprobieren.',
        'Ich darf mich schützen.',
        'Ich darf Freude empfinden.',
        'Ich sehe das Gute in mir.',
        'Ich nehme mich ernst.',
        'Ich darf meinen Weg suchen.',
        'Ich bin auf meiner Seite.',
        'Ich erlaube mir, zu wachsen.',
        'Ich bin es wert, gut behandelt zu werden.',
      ],
      AppConstants.levelAdvanced: [
        'Ich erkenne meinen Wert unabhängig von Meinungen.',
        'Ich feiere meine Fortschritte bewusst.',
        'Ich spreche klar für meine Bedürfnisse.',
        'Ich pflege Beziehungen, die mir guttun.',
        'Ich erlaube mir Erfolg.',
        'Ich achte meinen Körper und seine Signale.',
        'Ich vergebe mir und setze neu an.',
        'Ich investiere Zeit in mich.',
        'Ich nehme Komplimente an.',
        'Ich definiere mich nicht über Rückschläge.',
        'Ich wähle Umfelder, die mich stärken.',
        'Ich handle im Einklang mit meinen Werten.',
        'Ich setze Prioritäten für mein Wohl.',
        'Ich gönne mir Erholung ohne Schuldgefühl.',
        'Ich spreche über mich in wertschätzender Sprache.',
        'Ich vertraue meinen Fähigkeiten.',
        'Ich halte Vereinbarungen mit mir ein.',
        'Ich erlaube mir, groß zu denken.',
        'Ich bin verlässlich für mich selbst.',
        'Ich bin liebenswert – auch in Unvollkommenheit.',
      ],
      AppConstants.levelOpen: [
        'Mein Wert ist unverhandelbar.',
        'Ich lebe meine Einzigartigkeit sichtbar.',
        'Ich wähle groß, weil ich es mir wert bin.',
        'Ich empfange Fülle mit Dankbarkeit.',
        'Ich erzeuge Wert – für mich und andere.',
        'Ich bin Quelle von Selbstrespekt.',
        'Ich nähre mich auf allen Ebenen.',
        'Ich verkörpere Selbstannahme.',
        'Ich erwarte respektvolle Behandlung – und setze Grenzen.',
        'Ich ehre meine Geschichte und gestalte Zukunft.',
        'Ich bin mir selbst ein sicherer Ort.',
        'Ich vertraue meiner Würde in jeder Lage.',
        'Ich bejahe meine Größe ohne Überheblichkeit.',
        'Ich strahle Selbstliebe aus, die andere stärkt.',
        'Ich stehe zu meinem Wert in Entscheidungen.',
        'Ich wähle Beziehungen, die mich ehren.',
        'Ich bin Quelle von Stabilität in mir.',
        'Ich bin genug – und wachse weiter.',
        'Ich bin bedeutsam in dieser Welt.',
        'Ich feiere mein Sein.',
      ],
    },

    // Kategorie: Ängste lösen
    AppConstants.categoryAengste: {
      AppConstants.levelBeginner: [
        'Ich bin gerade sicher.',
        'Ich atme ruhig ein und aus.',
        'Angst ist ein Gefühl – es darf da sein und gehen.',
        'Ich kann langsamer werden.',
        'Ich finde heute einen kleinen Mut-Moment.',
        'Ich darf Pausen machen.',
        'Ich lenke meinen Blick auf das, was ich beeinflusse.',
        'Ich erde mich über meinen Atem.',
        'Ich wähle einen kleinen nächsten Schritt.',
        'Ich darf Unterstützung holen.',
        'Ich bin nicht alleine mit diesem Gefühl.',
        'Ich kann warten, bis die Welle abebbt.',
        'Ich bin freundlich zu mir, auch in Angst.',
        'Ich finde Halt im Jetzt.',
        'Ich erinnere mich: Ich habe schon vieles geschafft.',
        'Ich vertraue meinem Körper, sich zu beruhigen.',
        'Ich muss nichts beweisen.',
        'Ich darf heute weniger tun.',
        'Ich bin sicher genug, um weiterzuatmen.',
        'Ich erlaube mir, mich sicher zu fühlen.',
      ],
      AppConstants.levelAdvanced: [
        'Ich wähle Handeln trotz Unsicherheit.',
        'Ich bereite mich vor und gehe los.',
        'Ich zerlege große Aufgaben in kleine Schritte.',
        'Ich trainiere Mut wie einen Muskel.',
        'Ich ersetze Grübeln durch Tun.',
        'Ich prüfe Fakten statt Annahmen.',
        'Ich reframe Fehler als Feedback.',
        'Ich erlaube mir, sichtbar zu sein.',
        'Ich reguliere mich und spreche klar.',
        'Ich verlasse die Komfortzone bewusst.',
        'Ich organisiere Unterstützung.',
        'Ich halte Ungewissheit für eine Zeit aus.',
        'Ich erinnere mich an frühere Erfolge.',
        'Ich feiere jeden Mut-Moment.',
        'Ich stelle mich meinen Ängsten schrittweise.',
        'Ich bleibe im Kontakt mit meinem Körper.',
        'Ich entscheide und akzeptiere das Ergebnis.',
        'Ich bin größer als meine Angst.',
        'Ich vertraue meinem Umgang mit Stress.',
        'Ich bin mutig – in meinem Tempo.',
      ],
      AppConstants.levelOpen: [
        'Ich begegne Angst mit Neugier und Präsenz.',
        'Ich setze klare Ziele und schreite voran.',
        'Ich transformiere Druck in Fokus.',
        'Ich wähle Herausforderungen, die mich wachsen lassen.',
        'Ich handle furchtlos im Dienst meiner Werte.',
        'Ich führe mich selbst stabil durch Unsicherheit.',
        'Ich sehe Chancen, wo andere Grenzen sehen.',
        'Ich ruhe im Vertrauen in meine Fähigkeiten.',
        'Ich öffne Räume für Mut – für mich und andere.',
        'Ich bewege mich frei – innerlich und äußerlich.',
        'Ich antworte statt zu reagieren.',
        'Ich bleibe weit, auch wenn es eng wird.',
        'Ich nehme Risiken bewusst und klug.',
        'Ich bin sicher in mir – überall.',
        'Ich lasse Kontrollbedürfnis los und handle klar.',
        'Ich bin die Person, die ich früher gebraucht hätte.',
        'Ich inspiriere durch gelebten Mut.',
        'Ich wähle Freiheit, nicht Furcht.',
        'Ich schreibe meine Geschichte neu.',
        'Ich lebe angstfrei(er) Schritt für Schritt.',
      ],
    },

    // Kategorie: Eigene Ziele
    AppConstants.categoryCustom: {
      AppConstants.levelBeginner: [
        'Ich darf klein anfangen.',
        'Ich kläre heute einen nächsten Schritt.',
        'Ich wähle ein Ziel, das zu mir passt.',
        'Ich plane leicht und realistisch.',
        'Ich erlaube mir, Pausen einzuplanen.',
        'Ich darf Prioritäten setzen.',
        'Ich feiere jeden Mini-Fortschritt.',
        'Ich halte meine Schritte schriftlich fest.',
        'Ich mache jeden Tag ein bisschen.',
        'Ich sage freundlich „Nein" zu Ablenkungen.',
        'Ich lerne aus dem, was nicht klappt.',
        'Ich halte meine Energie im Blick.',
        'Ich starte unperfekt.',
        'Ich bitte um Unterstützung.',
        'Ich wähle den heute wichtigsten Schritt.',
        'Ich räume Hürden aus dem Weg – eine nach der anderen.',
        'Ich bleibe freundlich mit mir.',
        'Ich erkenne: Fortschritt ist genug.',
        'Ich darf umplanen.',
        'Ich komme an, indem ich gehe.',
      ],
      AppConstants.levelAdvanced: [
        'Ich arbeite fokussiert in klaren Blöcken.',
        'Ich schütze meine Spitzenzeiten.',
        'Ich beende, was ich beginne.',
        'Ich wähle die 20 % mit 80 % Wirkung.',
        'Ich delegiere, was nicht meins ist.',
        'Ich halte meine Zusagen – besonders mir selbst.',
        'Ich tracke Fortschritt sichtbar.',
        'Ich bade nicht im Perfektionismus.',
        'Ich löse Hindernisse strukturiert.',
        'Ich reflektiere kurz und optimiere.',
        'Ich bleibe konsistent, auch wenn die Motivation schwankt.',
        'Ich baue Gewohnheiten, die tragen.',
        'Ich schaffe mir störungsfreie Räume.',
        'Ich lerne schnell aus Feedback.',
        'Ich schließe jeden Tag mit einem Mini-Erfolg ab.',
        'Ich priorisiere mutig.',
        'Ich atme – dann handle ich.',
        'Ich sorge für Regeneration.',
        'Ich halte mein Zielbild lebendig.',
        'Ich ernte durch konsequentes Tun.',
      ],
      AppConstants.levelOpen: [
        'Ich richte mich an meiner Vision aus.',
        'Ich denke groß und handle konkret.',
        'Ich baue Systeme, die für mich arbeiten.',
        'Ich entscheide schnell und bewusst.',
        'Ich kreiere Mehrwert in jedem Schritt.',
        'Ich bündele Energie auf das Wesentliche.',
        'Ich führe mich und andere klar.',
        'Ich skaliere, was funktioniert.',
        'Ich baue Partnerschaften mit Wirkung.',
        'Ich meistere Rückschläge strategisch.',
        'Ich halte meinen inneren Kurs – unabhängig vom Außen.',
        'Ich investiere in langfristige Hebel.',
        'Ich lebe Exzellenz ohne Starrheit.',
        'Ich verkörpere meine Ziele.',
        'Ich tue heute, wofür ich morgen dankbar bin.',
        'Ich lasse los, was nicht mehr dient.',
        'Ich pflege Ruhe als Kraftquelle.',
        'Ich erweitere meinen Einfluss verantwortungsvoll.',
        'Ich feiere Ergebnisse und den Weg dorthin.',
        'Ich hinterlasse Spuren, die gut tun.',
      ],
    },
  };

  /// Gibt die Affirmationsvorschläge für eine bestimmte Kategorie und Level zurück
  static List<String> getSuggestions(String category, String level) {
    return suggestions[category]?[level] ?? [];
  }
}
